name: Continuous Integration (CI)

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v4

      - name: Configurar ambiente Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci --legacy-peer-deps

      - name: Executar Validação de Tipos e Build
        run: npm run build

      - name: Executar Testes Unitários
        run: npm run test:cov